
service: product-service
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

  stage: dev
  region: us-east-1

functions:
  getProductsList:
    handler: handlers/products.getProductsList
    events:
      - http:
          path: /products
          method: get
          cors: true

  getProductsById:
    handler: handlers/products.getProductsById
    events:
      - http:
          path: /products/{id}
          method: get
          cors: true

