service: product-service
frameworkVersion: '2'

plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

  environment:
    PG_HOST: ${env:PG_HOST}
    PG_PORT: ${env:PG_PORT}
    PG_DATABASE: ${env:PG_DATABASE}
    PG_USERNAME: ${env:PG_USERNAME}
    PG_PASSWORD: ${env:PG_PASSWORD}
    SNS_ARN:
      Ref: SNSTopic

  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action: "sqs:*"
      Resource: arn:aws:sqs:us-east-1:${env:ACCOUNT_ID}:catalogItemsQueue
    - Effect: "Allow"
      Action: "sns:*"
      Resource:
        Ref: SNSTopic

resources:
  Resources:
    SNSTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: createProductTopic
    SNSSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Endpoint: ${env:EMAIL}
        Protocol: email
        TopicArn:
          Ref: SNSTopic
    

functions:
  getProductsList:
    handler: handlers/products.getProductsList
    events:
      - http:
          path: /products
          method: get
          cors: true

  getProductsById:
    handler: handlers/products.getProductsById
    events:
      - http:
          path: /products/{id}
          method: get
          cors: true

  createProduct:
    handler: handlers/products.createProduct
    events:
      - http:
          path: /products
          method: post
          cors: true
  catalogBatchProcess:
    handler: handlers/catalogBatchProcess.handler
    events:
      - sqs:
          batchSize: 5
          arn: arn:aws:sqs:us-east-1:${env:ACCOUNT_ID}:catalogItemsQueue