service: import-service
frameworkVersion: '2'

plugins:
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

  environment:
    SQS_URL:
      Ref: SQSQueue

  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - s3:PutObject
      Resource: "arn:aws:s3:::rs-app-import-service"
    - Effect: "Allow"
      Action: "sqs:*"
      Resource:
        - Fn::GetAtt: [ SQSQueue, Arn ]

resources:
  Resources:
    SQSQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: catalogItemsQueue

functions:
  importProductsFile:
    handler: handler.importProductsFile
    events:
      - http:
          path: /import
          method: get
          cors: true
          request:
            querystrings:
              name: true
          authorizer:
            name: basicAuthorizer
            arn: arn:aws:lambda:${self:provider.region}:#{AWS::AccountId}:function:authorization-service-dev-basicAuthorizer
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
            type: token
  importFileParser:
    handler: handler.importFileParser
    events:
       - s3:
          bucket: rs-app-import-service
          existing: true
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
